"""empty message

Revision ID: 679c59e891c8
Revises: 473e0f77d7ad
Create Date: 2024-03-23 03:43:02.270151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679c59e891c8'
down_revision = '473e0f77d7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
